create table if not exists public.review_comments (
    id bigint generated by default as identity primary key,
    spot_id integer not null,
    author text not null default 'Anonym',
    comment_text text not null,
    is_approved boolean not null default false,
    created_at timestamptz not null default now(),
    constraint review_comments_comment_text_len check (char_length(comment_text) between 3 and 500),
    constraint review_comments_author_len check (char_length(author) between 2 and 40),
    constraint review_comments_no_links check (comment_text !~* '(https?://|www\.)')
);

alter table public.review_comments
    add column if not exists is_approved boolean not null default false;

create index if not exists review_comments_spot_id_created_at_idx
    on public.review_comments (spot_id, created_at desc);

create index if not exists review_comments_approved_spot_created_idx
    on public.review_comments (is_approved, spot_id, created_at desc);

alter table public.review_comments enable row level security;

drop policy if exists "Public can read review comments" on public.review_comments;
drop policy if exists "Public can insert review comments" on public.review_comments;

create policy "Public can read review comments"
    on public.review_comments
    for select
    to anon
    using (is_approved = true);

create policy "Public can insert review comments"
    on public.review_comments
    for insert
    to anon
    with check (
        spot_id > 0
        and char_length(author) between 2 and 40
        and char_length(comment_text) between 3 and 500
        and comment_text !~* '(https?://|www\.)'
        and (
            select count(*)
            from public.review_comments rc
            where lower(rc.author) = lower(review_comments.author)
              and rc.created_at > now() - interval '10 minutes'
        ) < 4
    );
