const kebabData = [
    {
        id: 2,
        name: "Rüyam",
        city: "Berlin",
        dish: "Gemüse-Döner",
        fleisch: 8.9,
        gemuese: 9.4,
        sosse: 9.3,
        brot: 9.4,
        balance: 9.3,
        auswahl: 9.3,
        portion: 9.5,
        hygiene: 8.8,
        service: 9.0,
        score: "92,10%",
        stars: "★★★★★",
        rank: 1,
        plIndex: "12,40%",
        image: "pictures/Rueyam.jpeg",
        kommentar: "Döner wurde mitgenommen und nicht frisch verzehrt",
        date: "28.02.2026"
    },
    {
        id: 3,
        name: "Sendlinger Spezial",
        city: "München",
        dish: "Steak-Döner",
        fleisch: 9.1,
        gemuese: 8.6,
        sosse: 8.4,
        brot: 9.2,
        balance: 8.4,
        auswahl: 8.3,
        portion: 9.4,
        hygiene: 8.8,
        service: 8.0,
        score: "86,90%",
        stars: "★★★★☆",
        rank: 2,
        plIndex: "8,30%",
        image: "pictures/SendlingerSpezial.jpeg",
        kommentar: "Wie Kleinduc schon sagte \"eher ein sandwich\"\nEs fehlte etwas sauer eingelegtes Gemüse",
        date: "11.04.2026"
    },
    {
        id: 4,
        name: "Taksim Steak Kebab Haus",
        city: "Dresden",
        dish: "Döner",
        fleisch: 8.7,
        gemuese: 8.6,
        sosse: 8.4,
        brot: 8.4,
        balance: 9.4,
        auswahl: 8.2,
        portion: 8.4,
        hygiene: 8.7,
        service: 9.0,
        score: "86,40%",
        stars: "★★★★☆",
        rank: 3,
        plIndex: "12,30%",
        image: "pictures/Taksim.jpeg",
        kommentar: "Hervorragende Balance - bis zum Ende noch Gemüse im Brot\nBrot war etwas zu crunchy und damit trocken",
        date: "24.04.2026"
    },
    {
        id: 5,
        name: "Bosporus Döner & Pizzeria",
        city: "Dresden",
        dish: "Steak-Döner",
        fleisch: 8.6,
        gemuese: 8.5,
        sosse: 8.4,
        brot: 8.8,
        balance: 8.2,
        auswahl: 8.5,
        portion: 8.9,
        hygiene: 8.5,
        service: 8.7,
        score: "85,70%",
        stars: "★★★★☆",
        rank: 4,
        plIndex: "9,50%",
        image: "pictures/Bosporus.jpeg",
        kommentar: "Gute portion aber geschmacklich nicht ganz harmonisch",
        date: "21.03.2026"
    },
    {
        id: 6,
        name: "Royal Pizza",
        city: "Dresden",
        dish: "Döner",
        fleisch: 8.3,
        gemuese: 9.3,
        sosse: 8.6,
        brot: 8.6,
        balance: 8.2,
        auswahl: 7.5,
        portion: 8.6,
        hygiene: 8.6,
        service: 8.8,
        score: "85,00%",
        stars: "★★★★☆",
        rank: 5,
        plIndex: "11,30%",
        image: "pictures/RoyalPizza.jpeg",
        kommentar: "Überraschend gut. Sogar mit Basilikum garniert",
        date: "18.04.2026"
    },
    {
        id: 7,
        name: "Kebab & Smash",
        city: "Gamisch-Partenkirchen",
        dish: "Döner",
        fleisch: 7.6,
        gemuese: 7.2,
        sosse: 6.1,
        brot: 7.2,
        balance: 6.3,
        auswahl: 7.2,
        portion: 7.8,
        hygiene: 8.3,
        service: 8.6,
        score: "73,70%",
        stars: "★★★★☆",
        rank: 6,
        plIndex: "8,70%",
        image: "pictures/Kebab-Smash.jpeg",
        kommentar: "Bei google ne 4,9 aber 100 % erkauft\nInsgesamt eine trockene Angelegenheit\nService war nett - Çay gab es for free",
        date: "06.04.2026"
    }
];
