const kebabData = [
    {
        id: 1,
        name: "Rüyam",
        city: "Berlin",
        dish: "Gemüse-Döner",
        fleisch: 8.9,
        gemuese: 9.4,
        sosse: 9.3,
        brot: 9.4,
        balance: 9.3,
        auswahl: 9.3,
        portion: 9.5,
        hygiene: 8.8,
        service: 9.0,
        score: "92,10%",
        stars: "★★★★★",
        rank: 1,
        preis: "7,40 €",
        plIndex: "12,40%",
        image: "pictures/berlin_rueyam.jpeg",
        kommentar: "Döner wurde mitgenommen und nicht ein mal frisch verzehrt. \nWas für eine herausragende Leistung. Wow. ",
        date: "28.02.2026",
        besuche: 1
    },
    {
        id: 2,
        name: "Med Dürüm",
        city: "Dresden",
        dish: "Döner",
        fleisch: 8.6,
        gemuese: 9.3,
        sosse: 9.4,
        brot: 9.8,
        balance: 8.3,
        auswahl: 8.5,
        portion: 9.2,
        hygiene: 9.2,
        service: 9.4,
        score: "90,80%",
        stars: "★★★★★",
        rank: 2,
        preis: "7,50 €",
        plIndex: "12,10%",
        image: "pictures/dresden_med_dueruem.jpg",
        kommentar: "Bestes selbstgebackenes Brot in ganz Dresden. \nAbsoluter all-time favorite in DD - Mir egal was die Planet-Bistro Anhänger sagen",
        date: "26.07.2025",
        besuche: 1
    },
    {
        id: 3,
        name: "Planet Bistro",
        city: "Dresden",
        dish: "Döner",
        fleisch: 9.1,
        gemuese: 9.4,
        sosse: 8.9,
        brot: 8.7,
        balance: 8.8,
        auswahl: 9.3,
        portion: 9.0,
        hygiene: 9.3,
        service: 8.7,
        score: "90,20%",
        stars: "★★★★★",
        rank: 3,
        preis: "6,50 €",
        plIndex: "13,90%",
        image: "pictures/dresden_planet_bistro.jpg",
        kommentar: "Wahrscheinlich der Bekannteste Spot in Dresden. Insgesamt einfach solid.\nMir war lediglich die ersten Male das Brot zu knusprig bzw. trocken.",
        date: "02.05.2025",
        besuche: 1
    },
    {
        id: 4,
        name: "Hugoo Gemüse Döner",
        city: "Leipzig",
        dish: "Gemüse-Döner",
        fleisch: 8.7,
        gemuese: 9.7,
        sosse: 9.2,
        brot: 9.2,
        balance: 9.7,
        auswahl: 8.9,
        portion: 8.2,
        hygiene: 8.7,
        service: 8.7,
        score: "90,00%",
        stars: "★★★★★",
        rank: 4,
        preis: "6,50 €",
        plIndex: "13,80%",
        image: "pictures/leipzig_hugoo_gemuese_doener.jpg",
        kommentar: "Döner mit ausgezeichnetem Gemüse (geil sauer) und Balance. \nLeider ist die Portion etwas klein, dennoch bester Döner in Leipzig bisher. ",
        date: "12.01.2025",
        besuche: 1
    },
    {
        id: 5,
        name: "Yaprak Döner by Istanbul Market",
        city: "Dresden",
        dish: "Steak-Döner",
        fleisch: 9.4,
        gemuese: 8.6,
        sosse: 8.4,
        brot: 8.3,
        balance: 8.7,
        auswahl: 8.5,
        portion: 8.9,
        hygiene: 8.7,
        service: 9.4,
        score: "87,70%",
        stars: "★★★★☆",
        rank: 5,
        preis: "10,50 €",
        plIndex: "8,40%",
        image: "pictures/dresden_yaprak_doener_by_istanbul_market.jpg",
        kommentar: "Sehr netter Inhaber. Man bekommt an der Theke i.d.R. eine Kostprobe vom Fleisch. \nOriginal Yaprak Döner mit nur Petersilie und Tomaten muss man mögen.",
        date: "13.08.2025",
        besuche: 1
    },
    {
        id: 6,
        name: "HUGOO DÖNER",
        city: "Dresden",
        dish: "Döner",
        fleisch: 8.8,
        gemuese: 9.1,
        sosse: 8.9,
        brot: 8.8,
        balance: 8.6,
        auswahl: 8.8,
        portion: 8.5,
        hygiene: 8.7,
        service: 8.5,
        score: "87,40%",
        stars: "★★★★☆",
        rank: 6,
        preis: "7,00 €",
        plIndex: "12,50%",
        image: "pictures/dresden_hugoo_doener.JPG",
        kommentar: "Sehr guter Döner aber mit Leistungsschwankungen (leider abh. von den Mitarbeitern).\nBesonders sind die frische Minze und der Spritzer Zitrus. Empfehlung ist raus!",
        date: "18.01.2025",
        besuche: 1
    },
    {
        id: 7,
        name: "Sendlinger Spezial",
        city: "München",
        dish: "Steak-Döner",
        fleisch: 9.1,
        gemuese: 8.6,
        sosse: 8.4,
        brot: 9.2,
        balance: 8.4,
        auswahl: 8.3,
        portion: 9.4,
        hygiene: 8.8,
        service: 8.0,
        score: "86,90%",
        stars: "★★★★☆",
        rank: 7,
        preis: "10,50 €",
        plIndex: "8,30%",
        image: "pictures/muenchen_sendlinger_spezial.jpeg",
        kommentar: "Es ist tatsächlich eher ein \"Sandwich\".\nMir fehlte wie immer das eingelegtes Gemüse. Vielleicht hab ich falsch bestellt.",
        date: "11.04.2026",
        besuche: 1
    },
    {
        id: 8,
        name: "Taksim Steak Kebab Haus",
        city: "Dresden",
        dish: "Döner",
        fleisch: 8.7,
        gemuese: 8.6,
        sosse: 8.4,
        brot: 8.4,
        balance: 9.4,
        auswahl: 8.2,
        portion: 8.4,
        hygiene: 8.7,
        service: 9.0,
        score: "86,40%",
        stars: "★★★★☆",
        rank: 8,
        preis: "7,00 €",
        plIndex: "12,30%",
        image: "pictures/dresden_taksim_steak_kebab_haus.jpeg",
        kommentar: "Hervorragende Balance - bis zum Ende noch Gemüse im Brot.\nBrot war für meinen Geschmack etwas zu crunchy und dry.",
        date: "24.04.2026",
        besuche: 1
    },
    {
        id: 9,
        name: "Bosporus Döner & Pizzeria",
        city: "Dresden",
        dish: "Steak-Döner",
        fleisch: 8.6,
        gemuese: 8.5,
        sosse: 8.4,
        brot: 8.8,
        balance: 8.2,
        auswahl: 8.5,
        portion: 8.9,
        hygiene: 8.5,
        service: 8.7,
        score: "85,70%",
        stars: "★★★★☆",
        rank: 9,
        preis: "9,00 €",
        plIndex: "9,50%",
        image: "pictures/dresden_bosporus.jpeg",
        kommentar: "Gute portion aber geschmacklich nicht ganz harmonisch.\nDen normalen Döner würde ich hier bevorzugen. On God.",
        date: "21.03.2026",
        besuche: 1
    },
    {
        id: 10,
        name: "Zagros Gemüsekebap",
        city: "Berlin",
        dish: "Gemüse-Döner",
        fleisch: 8.8,
        gemuese: 8.7,
        sosse: 8.6,
        brot: 8.5,
        balance: 8.1,
        auswahl: 8.2,
        portion: 8.8,
        hygiene: 8.9,
        service: 8.5,
        score: "85,70%",
        stars: "★★★★☆",
        rank: 9,
        preis: "7,00 €",
        plIndex: "12,20%",
        image: "pictures/berlin_zagros_gemuesekebap.jpeg",
        kommentar: "Etwas overhyped in meinen Augen aber für den Preis dennoch sehr gut.\nMir fehlte ganz klar die Säure bei so viel fettigen Fleisch (Spritzer Zitrone ist nicht genug) und die Kräuter (Zumak o.Ä.).",
        date: "31.12.2025",
        besuche: 1
    },
    {
        id: 11,
        name: "Royal Pizza",
        city: "Dresden",
        dish: "Döner",
        fleisch: 8.3,
        gemuese: 9.3,
        sosse: 8.6,
        brot: 8.6,
        balance: 8.2,
        auswahl: 7.5,
        portion: 8.6,
        hygiene: 8.6,
        service: 8.8,
        score: "85,00%",
        stars: "★★★★☆",
        rank: 11,
        preis: "7,50 €",
        plIndex: "11,30%",
        image: "pictures/dresden_royal_pizza.jpeg",
        kommentar: "Überraschend gut. Sogar mit Basilikum garniert. \nIn total eine solide Performance. ",
        date: "18.04.2026",
        besuche: 1
    },
    {
        id: 12,
        name: "Welat Döner",
        city: "Dresden",
        dish: "Döner",
        fleisch: 8.3,
        gemuese: 8.8,
        sosse: 8.2,
        brot: 8.2,
        balance: 8.7,
        auswahl: 8.3,
        portion: 8.7,
        hygiene: 8.6,
        service: 8.5,
        score: "84,80%",
        stars: "★★★★☆",
        rank: 12,
        preis: "7,00 €",
        plIndex: "12,10%",
        image: "pictures/dresden_welat_doener.jpeg",
        kommentar: "Guter Standard-Döner der immer rein geht. Was soll ich sagen.\nManchmal zu viel Soße aber sonst i. O. - Freitag gibt es immer Yaprak Spieß.",
        date: "19.06.2025",
        besuche: 1
    },
    {
        id: 13,
        name: "Mudi's Gemüse Döner",
        city: "Wolfsburg",
        dish: "Gemüse-Döner",
        fleisch: 7.9,
        gemuese: 7.7,
        sosse: 8.2,
        brot: 8.5,
        balance: 7.8,
        auswahl: 8.2,
        portion: 8.9,
        hygiene: 8.5,
        service: 8.3,
        score: "82,20%",
        stars: "★★★★☆",
        rank: 13,
        preis: "6,50 €",
        plIndex: "12,60%",
        image: "pictures/wolfsburg_mudis_gemuese_doener.JPG",
        kommentar: "Gute portion und schöne Anmutung. Geschmacklich leider eher mittelmaß. \nFleisch und Grillgemüse trieften in Öl. Wolfsburg ist somit nicht nur für mittelmäßige Autos bekannt.",
        date: "12.11.2025",
        besuche: 1
    },
    {
        id: 14,
        name: "Kebab & Smash",
        city: "Gamisch-Partenkirchen",
        dish: "Döner",
        fleisch: 7.6,
        gemuese: 7.2,
        sosse: 6.1,
        brot: 7.2,
        balance: 6.3,
        auswahl: 7.2,
        portion: 7.8,
        hygiene: 8.3,
        service: 8.6,
        score: "73,70%",
        stars: "★★★★☆",
        rank: 14,
        preis: "8,50 €",
        plIndex: "8,70%",
        image: "pictures/gamisch_kebab&smash.jpeg",
        kommentar: "Bei google eine 4,9 aber naja...\nInsgesamt eine trockene Angelegenheit.\nService war jedoch nett und es gab Çay for free.",
        date: "06.04.2026",
        besuche: 1
    }
];

const upcomingSpots = [
    { name: "Hans Kebab", city: "München" },
    { name: "Berlin'er Gemüse Döner", city: "Dresden" },
    { name: "Jami's Gemüse Kebab", city: "Dresden" },
    { name: "Der Dicke Schmidt Neustadt", city: "Dresden" },
    { name: "Golt'z kebap", city: "Berlin" }
];
