create table if not exists public.review_comments (
    id bigint generated by default as identity primary key,
    spot_id integer not null,
    author text not null default 'Anonym',
    comment_text text not null,
    is_approved boolean not null default false,
    created_at timestamptz not null default now(),
    constraint review_comments_comment_text_len check (char_length(comment_text) between 3 and 500),
    constraint review_comments_author_len check (char_length(author) between 2 and 40),
    constraint review_comments_no_links check (comment_text !~* '(https?://|www\.)')
);

alter table public.review_comments
    add column if not exists is_approved boolean not null default false;

create index if not exists review_comments_spot_id_created_at_idx
    on public.review_comments (spot_id, created_at desc);

create index if not exists review_comments_approved_spot_created_idx
    on public.review_comments (is_approved, spot_id, created_at desc);

alter table public.review_comments enable row level security;

drop policy if exists "Public can read review comments" on public.review_comments;
drop policy if exists "Public can insert review comments" on public.review_comments;

create policy "Public can read review comments"
    on public.review_comments
    for select
    to anon
    using (is_approved = true);

create policy "Public can insert review comments"
    on public.review_comments
    for insert
    to anon
    with check (
        spot_id > 0
        and char_length(author) between 2 and 40
        and char_length(comment_text) between 3 and 500
        and comment_text !~* '(https?://|www\.)'
    );

create table if not exists public.review_spot_likes (
    id bigint generated by default as identity primary key,
    spot_id integer not null,
    voter_fingerprint text not null,
    created_at timestamptz not null default now(),
    constraint review_spot_likes_spot_positive check (spot_id > 0),
    constraint review_spot_likes_voter_len check (char_length(voter_fingerprint) between 12 and 120),
    constraint review_spot_likes_unique_vote unique (spot_id, voter_fingerprint)
);

create index if not exists review_spot_likes_spot_id_idx
    on public.review_spot_likes (spot_id, created_at desc);

alter table public.review_spot_likes enable row level security;

drop policy if exists "Public can read review spot likes" on public.review_spot_likes;
drop policy if exists "Public can insert review spot likes" on public.review_spot_likes;

create policy "Public can read review spot likes"
    on public.review_spot_likes
    for select
    to anon
    using (true);

create policy "Public can insert review spot likes"
    on public.review_spot_likes
    for insert
    to anon
    with check (
        spot_id > 0
        and char_length(voter_fingerprint) between 12 and 120
    );

create table if not exists public.community_reviews (
    id bigint generated by default as identity primary key,
    reviewer_name text not null,
    spot_name text not null,
    city text not null,
    dish text not null,
    visit_date date not null,
    fleisch numeric(3,1) not null,
    gemuese numeric(3,1) not null,
    sosse numeric(3,1) not null,
    brot numeric(3,1) not null,
    balance numeric(3,1) not null,
    auswahl numeric(3,1) not null,
    portion numeric(3,1) not null,
    hygiene numeric(3,1) not null,
    service numeric(3,1) not null,
    comment_text text not null,
    image_url text not null,
    is_approved boolean not null default false,
    created_at timestamptz not null default now(),
    constraint community_reviews_name_len check (char_length(reviewer_name) between 2 and 40),
    constraint community_reviews_spot_len check (char_length(spot_name) between 2 and 80),
    constraint community_reviews_city_len check (char_length(city) between 2 and 60),
    constraint community_reviews_dish_len check (char_length(dish) between 2 and 60),
    constraint community_reviews_comment_len check (char_length(comment_text) between 15 and 1000),
    constraint community_reviews_image_url_len check (char_length(image_url) between 12 and 1024),
    constraint community_reviews_fleisch_range check (fleisch between 1 and 10),
    constraint community_reviews_gemuese_range check (gemuese between 1 and 10),
    constraint community_reviews_sosse_range check (sosse between 1 and 10),
    constraint community_reviews_brot_range check (brot between 1 and 10),
    constraint community_reviews_balance_range check (balance between 1 and 10),
    constraint community_reviews_auswahl_range check (auswahl between 1 and 10),
    constraint community_reviews_portion_range check (portion between 1 and 10),
    constraint community_reviews_hygiene_range check (hygiene between 1 and 10),
    constraint community_reviews_service_range check (service between 1 and 10),
    constraint community_reviews_no_links check (comment_text !~* '(https?://|www\.)')
);

create index if not exists community_reviews_approved_created_idx
    on public.community_reviews (is_approved, created_at desc);

-- Add new columns if they don't exist
alter table public.community_reviews
    add column if not exists preis text;

alter table public.community_reviews
    add column if not exists verzehrort text;

alter table public.community_reviews enable row level security;

drop policy if exists "Public can read approved community reviews" on public.community_reviews;
drop policy if exists "Public can insert community reviews" on public.community_reviews;

create policy "Public can read approved community reviews"
    on public.community_reviews
    for select
    to anon
    using (is_approved = true);

create policy "Public can insert community reviews"
    on public.community_reviews
    for insert
    to anon
    with check (
        char_length(reviewer_name) between 2 and 40
        and char_length(spot_name) between 2 and 80
        and char_length(city) between 2 and 60
        and char_length(dish) between 2 and 60
        and char_length(comment_text) between 15 and 1000
        and char_length(image_url) between 12 and 1024
        and comment_text !~* '(https?://|www\.)'
        and fleisch between 1 and 10
        and gemuese between 1 and 10
        and sosse between 1 and 10
        and brot between 1 and 10
        and balance between 1 and 10
        and auswahl between 1 and 10
        and portion between 1 and 10
        and hygiene between 1 and 10
        and service between 1 and 10
    );

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'community-review-images',
    'community-review-images',
    true,
    6291456,
    array['image/jpeg', 'image/png', 'image/webp', 'image/heic']
)
on conflict (id) do nothing;

drop policy if exists "Public can read community review images" on storage.objects;
drop policy if exists "Public can upload community review images" on storage.objects;

create policy "Public can read community review images"
    on storage.objects
    for select
    to anon
    using (bucket_id = 'community-review-images');

create policy "Public can upload community review images"
    on storage.objects
    for insert
    to anon
    with check (
        bucket_id = 'community-review-images'
        and (storage.foldername(name))[1] = 'public'
    );
