const fs = require('fs');
const path = require('path');

const SCRIPT_PATH = path.join(__dirname, '../../assets/js/script.js');
const UTILS_PATH = path.join(__dirname, '../../assets/js/utils.js');

const FUNCTIONS_TO_EXTRACT = [
    'getColorForScore',
    'escapeHtml',
    'normalizeCommentText',
    'formatCommentDate',
    'renderStars',
    'parsePercentNumber',
    'parseEuroNumber',
    'formatPercentNumber',
    'formatEuroNumber',
    'normalizeSpotScoreDisplay',
    'buildSpotKey',
    'formatVisitDate',
    'getTodayIsoDate',
    'buildCommunityAverage'
];

// Special regex for simple one-liners like parseVal
const CONSTANTS_TO_EXTRACT = [
    'parseVal'
];

function extractFunction(content, name) {
    const regex = new RegExp(`function\\s+${name}\\s*\\(`, 'g');
    const match = regex.exec(content);
    if (!match) return null;

    const startIdx = match.index;
    let braceCount = 0;
    let started = false;
    let endIdx = -1;

    for (let i = startIdx; i < content.length; i++) {
        if (content[i] === '{') {
            braceCount++;
            started = true;
        } else if (content[i] === '}') {
            braceCount--;
        }

        if (started && braceCount === 0) {
            endIdx = i + 1;
            break;
        }
    }

    if (endIdx === -1) return null;
    return content.substring(startIdx, endIdx);
}

function extractConstant(content, name) {
    // Looks for: const parseVal = (s) => ... ;
    const regex = new RegExp(`(const|let|var)\\s+${name}\\s*=\\s*[^;]+;`, 'g');
    const match = regex.exec(content);
    if (!match) return null;
    return match[0];
}

try {
    console.log(`Reading ${SCRIPT_PATH}...`);
    const content = fs.readFileSync(SCRIPT_PATH, 'utf8');
    const exports = [];

    for (const name of FUNCTIONS_TO_EXTRACT) {
        const fnContent = extractFunction(content, name);
        if (fnContent) {
            exports.push(`export ${fnContent}`);
            console.log(`✅ Extracted function: ${name}`);
        } else {
            console.warn(`⚠️ Warning: Could not find function ${name}`);
        }
    }

    for (const name of CONSTANTS_TO_EXTRACT) {
        const constContent = extractConstant(content, name);
        if (constContent) {
            // Remove const/let/var and replace with export const
            const cleaned = constContent.replace(/^(const|let|var)\s+/, 'export const ');
            exports.push(cleaned);
            console.log(`✅ Extracted constant: ${name}`);
        } else {
            console.warn(`⚠️ Warning: Could not find constant ${name}`);
        }
    }

    // Add some helper functions that might not be in script.js but are needed by tests
    // or were previously in utils.js. If they are in script.js, we should extract them instead.
    
    // Check if we extracted everything we need for existing tests
    if (!exports.some(e => e.includes('getColorForScore'))) {
        throw new Error('Critical function getColorForScore not found!');
    }

    const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by tests/helpers/sync-utils.js
 * Extracted from assets/js/script.js
 */

${exports.join('\n\n')}

/**
 * Additional helpers for testing
 */

export function parseDateDDMMYYYY(dateStr) {
    if (!dateStr || typeof dateStr !== 'string') return new Date(0);
    const parts = dateStr.split('.');
    if (parts.length !== 3) return new Date(0);
    const [day, month, year] = parts;
    const d = new Date(\`\${year}-\${month}-\${day}\`);
    return isNaN(d.getTime()) ? new Date(0) : d;
}

export function calcPlIndex(score, preis) {
    // Use the extracted parseVal if available
    const pVal = typeof parseVal !== 'undefined' ? parseVal : (s) => parseFloat(String(s).replace(',', '.').replace('%', '').replace(' €', '')) || 0;
    const parsedScore = pVal(score);
    const parsedPreis = pVal(preis);
    if (parsedPreis === 0) return null;
    return parseFloat((parsedScore / parsedPreis).toFixed(2));
}

export function renderStarsScore(scoreStr) {
    if (!scoreStr) return null;
    return parseFloat(String(scoreStr).replace(',', '.').replace('%', ''));
}

export function isScoreInRange(val) {
    return typeof val === 'number' && isFinite(val) && val >= 1 && val <= 10;
}
`;

    fs.writeFileSync(UTILS_PATH, output);
    console.log(`✅ Successfully wrote ${UTILS_PATH}`);

} catch (err) {
    console.error(`❌ Error during extraction: ${err.message}`);
    process.exit(1);
}
